services:
  mysql:
    image: mysql:8.0
    container_name: cinema-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tnwlssql1!
      MYSQL_DATABASE: hh99_cinema_sj
      TZ: Asia/Seoul
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
